id: P007840
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4194
  title: རྗེ་བཙུན་ཤེས་རབ་སེངྒེའི་རྟོགས་བརྗོད་སྐལ་བཟང་དད་པའི་འདོད་འཇོ་དཔག་བསམ་ཡོངས་འདུའི་ཁྲི་ཤིང
  author: ''
  volumes:
    45e17b44747e452081a6e3ef91b999bb:
      image_group_id: I1PD96711
      title: ''
      volume_number: 1
      total_pages: 130
ebook_metadata:
  title: རྗེ་བཙུན་ཤེས་རབ་སེངྒེའི་རྟོགས་བརྗོད་སྐལ་བཟང་དད་པའི་འདོད་འཇོ་དཔག་བསམ་ཡོངས་འདུའི་ཁྲི་ཤིང
  author: ''
  sku: P007840
  cover: cover.jpg
  layers:
  - pagination
