id: P007840
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG4194
  title: རྗེ་བཙུན་ཤེས་རབ་སེངྒེའི་རྟོགས་བརྗོད་སྐལ་བཟང་དད་པའི་འདོད་འཇོ་དཔག་བསམ་ཡོངས་འདུའི་ཁྲི་ཤིང
  author: ''
  volumes:
    2b9b5facb0454e35af2fdd17571d70fb:
      image_group_id: I1PD96711
      title: Volume 1 of rje btsun shes rab seng+ge'i rtogs pa brjod pa skal bzang
        dad pa'i 'dod 'jo dpag bsam yongs 'du'i khri shing
      volume_number: 1
      total_pages: 130
      base_file: v001.txt
