id: I594B4DC6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:42:17+00:00'
last_modified: '2022-06-09T06:27:13.858933+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4194
  title: རྗེ་བཙུན་ཤེས་རབ་སེངྒེའི་རྟོགས་བརྗོད་སྐལ་བཟང་དད་པའི་འདོད་འཇོ་དཔག་བསམ་ཡོངས་འདུའི་ཁྲི་ཤིང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0ACA:
      image_group_id: I1PD96711
      title: Volume 1 of rje btsun shes rab seng+ge'i rtogs pa brjod pa skal bzang
        dad pa'i 'dod 'jo dpag bsam yongs 'du'i khri shing
      total_pages: 130
      order: 1
      base_file: 0ACA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
